spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

  cache:
    type: none

logging:
  level:
    root: WARN
    com.linksplit: DEBUG
    org.springframework.security: DEBUG

app:
  base-url: http://test.linksplit.com
  view-fraud-prevention:
    enabled: false