spring:
  application:
    name: linksplit

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://db.vcwireorjflemkupqacv.supabase.co:5432/postgres?user=postgres&password=/9i36X-E.C6JPNy}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:/9i36X-E.C6JPNy}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
    show-sql: false
    open-in-view: false

  thymeleaf:
    cache: true
    mode: HTML

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=60m

server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

logging:
  level:
    root: INFO
    com.linksplit: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: WARN

app:
  base-url: ${BASE_URL:https://frwrd.pro}
  shortcode-length: 6
  ad-display-seconds: 5
  cpm-rate: ${CPM_RATE:1.00}
  revenue-share: ${REVENUE_SHARE:0.50}
  view-fraud-prevention:
    enabled: true
    rate-limits:
      five-minutes:
        duration-minutes: 5
        max-views: 5
      hourly:
        duration-minutes: 60
        max-views: 20
      daily:
        duration-minutes: 1440
        max-views: 50

supabase:
  url: ${SUPABASE_URL:https://vcwireorjflemkupqacv.supabase.co}
  publishable-key: sb_publishable_Lcqp9RlUSmyKUj2UUByD0w_XMjqqdSx
  secret-key: sb_secret_mmph-Y5jyH6FwDajE_OUSQ_i11ya8DA
  jwks:
    discovery-url: https://vcwireorjflemkupqacv.supabase.co/auth/v1/.well-known/jwks.json
    key-id: efee2fc1-60a4-4411-ab59-6bc7a7b99e70
    public-key:
      x: DRhskqQNxJpUCcO9FOJBbqMkBVOfpOoR_b3v7HBSn3o
      y: COKdHm_5vvIi-FEnT31mwfp9ZgCBc9hcPwtY28Fiu9U
      alg: ES256
      crv: P-256
      ext: true
      kid: efee2fc1-60a4-4411-ab59-6bc7a7b99e70
      kty: EC